feat(checker): implement TS2523 for yield in parameter initializer
Added check to emit TS2523 when 'yield' is used in a parameter's default
value initializer. This mirrors the existing TS2524 check for 'await'.

Example error case:
  function* foo(x = yield 1) {}  // Error TS2523

Affects 4 conformance tests based on co-occurrence analysis.